name: rectangle_detector
description: Flutter plugin to detect edges of objects, scan paper, and detect rectangle. Using OpenCV for Android and and VisionKit IOS.
version: 0.0.1
homepage: https://github.com/oddbit/flutter_rectangle_detector

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: id.oddbit.rectangle_detector.rectangle_detector
        pluginClass: RectangleDetectorPlugin
      ios:
        pluginClass: RectangleDetectorPlugin

